/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ZramMeter
#define HEADER_ZramMeter
/*
htop - ZramMeter.h
(C) 2004-2016 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int ZramMeter_attributes[];

extern MeterClass ZramMeter_class;

#endif
